Controllers/EnquiryEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieCineplex.Models;
using Microsoft.AspNetCore.Http;

namespace MovieCineplex.Controllers
{
    public class EnquiryEventsController : Controller
    {
        private readonly ABCDataContext _context;

        public EnquiryEventsController(ABCDataContext context)
        {
            _context = context;    
        }

        // GET: EnquiryEvents
        public async Task<IActionResult> Index()
        {
            String userName = HttpContext.Session.GetString("userName");
            Enquiry enquiry = await _context.Enquiry.SingleOrDefaultAsync(m => m.Email == userName);
            if (enquiry == null)
            {
                Enquiry en = new Enquiry();
                en.Email = userName;
                en.Message = "";
                _context.Add(en);
                await _context.SaveChangesAsync();
                enquiry = await _context.Enquiry.SingleOrDefaultAsync(m => m.Email == userName);
            }
            
            var aBCDataContext = _context.EnquiryEvents.Include(e => e.Enquiry).Include(e => e.Events);
            return View(await aBCDataContext.Where(e =>e.EnquiryId== enquiry.EnquiryId).ToListAsync());
        }

        // GET: EnquiryEvents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enquiryEvents = await _context.EnquiryEvents.SingleOrDefaultAsync(m => m.EventsId == id);
            if (enquiryEvents == null)
            {
                return NotFound();
            }

            return View(enquiryEvents);
        }

        // GET: EnquiryEvents/Create
        public async Task<IActionResult> Create(int? id)
        {
            if(HttpContext.Session.GetString("userName")==null)
            ViewData["logintest"] = "0";
            else
                ViewData["logintest"] = "1";
            ViewData["event"] = id;

            EnquiryEvents enquiryEvent = await _context.EnquiryEvents.Include(e =>e.Events)
                .SingleOrDefaultAsync(m => m.EventsId == id);
            EventsInfo even = enquiryEvent.Events;
            ViewData["eventInfo"] = even.Information;

            return View();
        }

        // POST: EnquiryEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventsId,EnquiryId")] EnquiryEvents enquiryEvents)
        {
            if (ModelState.IsValid)
            {
                String userName = HttpContext.Session.GetString("userName");
                Enquiry enquiry = await _context.Enquiry.SingleOrDefaultAsync(m => m.Email == userName);
                if (enquiry == null)
                {
                    Enquiry en = new Enquiry();
                    en.Email = userName;
                    en.Message = "";
                    _context.Add(en);
                    await _context.SaveChangesAsync();
                    enquiry = await _context.Enquiry.SingleOrDefaultAsync(m => m.Email == userName);
                }
                enquiryEvents.EnquiryId = enquiry.EnquiryId;

                EnquiryEvents existEvent= await _context.EnquiryEvents.SingleOrDefaultAsync(e=>e.EnquiryId== enquiry.EnquiryId && e.EventsId== enquiryEvents.EventsId);
                if(existEvent!=null)
                    return RedirectToAction("Index");
                _context.Add(enquiryEvents);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["EnquiryId"] = new SelectList(_context.Enquiry, "EnquiryId", "Email", enquiryEvents.EnquiryId);
            ViewData["EventsId"] = new SelectList(_context.EventsInfo, "EventsId", "EventsId", enquiryEvents.EventsId);
            return View(enquiryEvents);
        }

        // GET: EnquiryEvents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enquiryEvents = await _context.EnquiryEvents.SingleOrDefaultAsync(m => m.EventsId == id);
            if (enquiryEvents == null)
            {
                return NotFound();
            }
            ViewData["EnquiryId"] = new SelectList(_context.Enquiry, "EnquiryId", "Email", enquiryEvents.EnquiryId);
            ViewData["EventsId"] = new SelectList(_context.EventsInfo, "EventsId", "EventsId", enquiryEvents.EventsId);
            return View(enquiryEvents);
        }

        // POST: EnquiryEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventsId,EnquiryId")] EnquiryEvents enquiryEvents)
        {
            if (id != enquiryEvents.EventsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enquiryEvents);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnquiryEventsExists(enquiryEvents.EventsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["EnquiryId"] = new SelectList(_context.Enquiry, "EnquiryId", "Email", enquiryEvents.EnquiryId);
            ViewData["EventsId"] = new SelectList(_context.EventsInfo, "EventsId", "EventsId", enquiryEvents.EventsId);
            return View(enquiryEvents);
        }

        // GET: EnquiryEvents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enquiryEvents = await _context.EnquiryEvents.SingleOrDefaultAsync(m => m.EventsId == id);
            if (enquiryEvents == null)
            {
                return NotFound();
            }

            return View(enquiryEvents);
        }

        // POST: EnquiryEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enquiryEvents = await _context.EnquiryEvents.SingleOrDefaultAsync(m => m.EventsId == id);
            _context.EnquiryEvents.Remove(enquiryEvents);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool EnquiryEventsExists(int id)
        {
            return _context.EnquiryEvents.Any(e => e.EventsId == id);
        }
    }
}

Controllers/EventsInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieCineplex.Models;

namespace MovieCineplex.Controllers
{
    public class EventsInfoesController : Controller
    {
        private readonly ABCDataContext _context;

        public EventsInfoesController(ABCDataContext context)
        {
            _context = context;    
        }

        // GET: EventsInfoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.EventsInfo.ToListAsync());
        }

        // GET: EventsInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventsInfo = await _context.EventsInfo.SingleOrDefaultAsync(m => m.EventsId == id);
            if (eventsInfo == null)
            {
                return NotFound();
            }

            return View(eventsInfo);
        }

        // GET: EventsInfoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventsInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventsId,Information")] EventsInfo eventsInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventsInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(eventsInfo);
        }

        // GET: EventsInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventsInfo = await _context.EventsInfo.SingleOrDefaultAsync(m => m.EventsId == id);
            if (eventsInfo == null)
            {
                return NotFound();
            }
            return View(eventsInfo);
        }

        // POST: EventsInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventsId,Information")] EventsInfo eventsInfo)
        {
            if (id != eventsInfo.EventsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventsInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventsInfoExists(eventsInfo.EventsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(eventsInfo);
        }

        // GET: EventsInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventsInfo = await _context.EventsInfo.SingleOrDefaultAsync(m => m.EventsId == id);
            if (eventsInfo == null)
            {
                return NotFound();
            }

            return View(eventsInfo);
        }

        // POST: EventsInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventsInfo = await _context.EventsInfo.SingleOrDefaultAsync(m => m.EventsId == id);
            _context.EventsInfo.Remove(eventsInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool EventsInfoExists(int id)
        {
            return _context.EventsInfo.Any(e => e.EventsId == id);
        }
    }
}

Views/EventsInfoes/Create.cshtml
@model MovieCineplex.Models.EventsInfo

@{
    ViewData["Title"] = "Create";
}

<h2>Book this event</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>EventsInfo</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Information" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Information" class="form-control" />
                <span asp-validation-for="Information" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EventsInfoes/Delete.cshtml
@model MovieCineplex.Models.EventsInfo

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventsInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Information)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Information)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Views/EventsInfoes/Details.cshtml
@model MovieCineplex.Models.EventsInfo

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>EventsInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Information)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Information)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventsId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/EventsInfoes/Edit.cshtml
@model MovieCineplex.Models.EventsInfo

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>EventsInfo</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="EventsId" />
        <div class="form-group">
            <label asp-for="Information" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Information" class="form-control" />
                <span asp-validation-for="Information" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EventsInfoes/Index.cshtml
@model IEnumerable<MovieCineplex.Models.EventsInfo>

@{
    ViewData["Title"] = "Index";
}

<h2>FIND MORE FUN WITH US</h2>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Information)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Information)
            </td>
            <td>
                <a asp-controller="EnquiryEvents" asp-action="Create" asp-route-id="@item.EventsId">Book This Event</a>
            </td>
        </tr>
}
    </tbody>
</table>